"""
Create tab endpoints — Blank Page Solver + Caption Generator + Image Direction.

All Granite calls are synchronous (Ollama), so endpoints use plain `def`
(not `async def`). FastAPI automatically runs sync endpoints in a thread
pool, keeping the event loop unblocked.
"""

from typing import Any, Literal

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel

from api.dependencies import (
    get_caption_generator,
    get_direction_generator,
    get_image_generator,
    get_moment_analyzer,
    get_script_generator,
    get_voice_refiner,
)

router = APIRouter()


# ── Request / Response models ─────────────────────────────────────────────────

class AnalyzeMomentRequest(BaseModel):
    moment_text: str


class DirectionsRequest(BaseModel):
    moment_analysis: dict[str, Any]
    moment_text: str


class CaptionsRequest(BaseModel):
    product: str
    occasion: str
    desired_feel: str = ""
    cluster_id: int = 0
    previous_captions: list[str] = []


class ScriptRequest(BaseModel):
    reference_caption: str
    views: int = 0
    reach: int = 0
    likes: int = 0
    comments: int = 0
    shares: int = 0
    saves: int = 0
    format: Literal["Reel", "Carousel", "Static"] = "Reel"
    cluster_id: int = 0


class ImagePromptRequest(BaseModel):
    caption: str
    product: str


class VoiceRefineRequest(BaseModel):
    transcript: str
    cluster_id: int = 0


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.post("/analyze-moment")
def analyze_moment(req: AnalyzeMomentRequest) -> dict:
    """
    Granite Call #6 — MomentAnalyzer.
    Extracts emotional_core, business_signal, best_cluster_id, cluster_reason.
    """
    if not req.moment_text.strip():
        raise HTTPException(status_code=422, detail="moment_text is required")
    return get_moment_analyzer().analyze(req.moment_text)


@router.post("/directions")
def generate_directions(req: DirectionsRequest) -> list:
    """
    Granite Call #7 — DirectionGenerator.
    Returns 3 distinct creative directions.
    """
    if not req.moment_text.strip():
        raise HTTPException(status_code=422, detail="moment_text is required")
    return get_direction_generator().generate(req.moment_analysis, req.moment_text)


@router.post("/captions")
def generate_captions(req: CaptionsRequest) -> list:
    """
    Granite Call #2 — CaptionGenerator.
    Returns 3 caption variants with per-attribute reasoning.
    """
    if not req.product.strip():
        raise HTTPException(status_code=422, detail="product is required")
    if not req.occasion.strip():
        raise HTTPException(status_code=422, detail="occasion is required")
    return get_caption_generator().generate(
        product           = req.product.strip(),
        occasion          = req.occasion.strip(),
        desired_feel      = req.desired_feel.strip() or "on-brand and engaging",
        cluster_id        = req.cluster_id,
        previous_captions = req.previous_captions or None,
    )


@router.post("/script")
def generate_script(req: ScriptRequest) -> dict:
    """
    Granite Call #9 — ScriptGenerator (structure) + CaptionGenerator (caption).
    Returns a structured content script (Reel/Carousel/Static) inspired by a
    high-performing reference post. The caption field is generated by the
    CaptionGenerator for quality parity with the Caption Brief.
    """
    if not req.reference_caption.strip():
        raise HTTPException(status_code=422, detail="reference_caption is required")

    script = get_script_generator().generate(
        reference_caption = req.reference_caption.strip(),
        metrics           = {
            "views"   : req.views,
            "reach"   : req.reach,
            "likes"   : req.likes,
            "comments": req.comments,
            "shares"  : req.shares,
            "saves"   : req.saves,
        },
        content_format = req.format,
        cluster_id     = req.cluster_id,
    )

    # Replace the script-generated caption with a high-quality one from
    # CaptionGenerator — same prompt and logic as the Caption Brief tab.
    # Use the script's hook as product context (it captures what the new
    # post is actually about) and the cluster's tone as the desired feel.
    try:
        cap_gen = get_caption_generator()
        clusters = cap_gen.cluster_profiles()
        cluster_profile = next(
            (c for c in clusters if c["cluster_id"] == req.cluster_id),
            clusters[0],
        )
        tone = cluster_profile["profile"].get("tone_descriptors", [])
        desired_feel = ", ".join(tone[:3]) if tone else "on-brand and engaging"

        hook = script.get("hook") or req.reference_caption[:100]
        captions = cap_gen.generate(
            product      = hook,
            occasion     = f"New {req.format} post",
            desired_feel = desired_feel,
            cluster_id   = req.cluster_id,
        )
        if captions:
            script["caption"] = captions[0]["caption"]
    except Exception:
        pass  # keep the script-generated caption as fallback

    return script


@router.post("/voice-refine")
def voice_refine(req: VoiceRefineRequest) -> dict:
    """
    Granite Call #12 — VoiceRefiner.
    Takes a raw spoken transcript and returns a polished on-brand caption
    calibrated to the given content cluster's brand voice.
    """
    if not req.transcript.strip():
        raise HTTPException(status_code=422, detail="transcript is required")

    import json
    from pathlib import Path
    _PROFILE_PATH = Path(__file__).resolve().parent.parent.parent / "data" / "brand_profile.json"
    try:
        brand_profile = json.loads(_PROFILE_PATH.read_text(encoding="utf-8"))
    except Exception as exc:
        raise HTTPException(status_code=503, detail=f"Brand profile not found: {exc}")

    return get_voice_refiner().refine(
        transcript   = req.transcript.strip(),
        cluster_id   = req.cluster_id,
        brand_profile= brand_profile,
    )


@router.post("/image-prompt")
def generate_image_prompt(req: ImagePromptRequest) -> dict:
    """
    Granite Call #3 — ImagePromptGenerator.
    Returns {prompt, style_notes} for Midjourney / DALL-E 3.
    """
    if not req.caption.strip():
        raise HTTPException(status_code=422, detail="caption is required")
    return get_image_generator().generate(
        caption = req.caption.strip(),
        product = req.product.strip(),
    )
