"""
Critic / Editorial Agent — Granite invocations #18 (critique pass) + #21 (classifier).

WHAT CHANGED AND WHY:
The original _classify() used Granite to freely generate a fix_direction sentence,
which produced vague instructions like "make it more authentic." The CopywritingAgent
couldn't reliably act on that. Now:

1. Granite still classifies the error TYPE (that part worked fine).
2. fix_direction is now overridden with a DETERMINISTIC, signal-specific rewrite
   instruction mapped from the error type. Granite's generated fix_direction is
   preserved as granite_fix_hint in the output for logging, but the orchestrator's
   CopywritingAgent receives the structured directive.
3. The ai_slop classifier prompt is extended with explicit hook-pattern examples so
   Granite can distinguish "sounds AI but has a good hook" from "structurally generic."

Architecture (ACL 2025 RAG-Critic pattern, coarse-to-fine — unchanged):
  Step 1 — BrandGuardian.critique() identifies WHAT is wrong (issues list).
  Step 2 — ErrorClassifier (Granite call) maps the issues to ONE typed error category.
  Step 3 — Return CriticResult with error_type, structured fix_direction, routing_target.

Error taxonomy (unchanged — orchestrator routing depends on these exact strings):
  ai_slop         → CopywritingAgent.rewrite_caption
  off_brand_vocab → BrandVoiceAgent.enforce_vocabulary
  wrong_platform  → CopywritingAgent.reformat_caption
  factual_gap     → human_review_flag = True (no auto-route)
  approved        → no action
"""

from __future__ import annotations

import json
import re

from langchain_core.prompts import PromptTemplate
from langchain_ollama import OllamaLLM

from src.agents.base import (
    AgentResult,
    AgentTask,
    BaseAgent,
    OLLAMA_MODEL,
    ROUTING_TARGETS,
)

# ---------------------------------------------------------------------------
# Signal-specific rewrite directives (deterministic — NOT generated by Granite)
# These are the instructions CopywritingAgent receives as fix_direction.
# They are concrete enough for an 8B model to execute reliably.
# ---------------------------------------------------------------------------

_SIGNAL_REPAIR_DIRECTIVES: dict[str, str] = {
    "ai_slop": (
        "Rewrite the hook (first line) using ONE of these structural patterns: "
        "(1) Number-led: 'X reasons your Y keeps Z.' "
        "(2) Result-first: 'How I [achieved outcome] with [specific thing].' "
        "(3) POV scenario: 'POV: You [relatable situation] and [unexpected result].' "
        "(4) Exclusivity: 'The [profession] trick nobody talks about.' "
        "Strip all filler phrases ('amazing', 'delicious', 'in today's world', "
        "'game-changer', 'so excited'). The first 8 words must create a curiosity gap "
        "or state a result the viewer wants. Do not start with a greeting."
    ),
    "off_brand_vocab": (
        "Replace every avoided term with a word from the brand's recurring_words list. "
        "Match the tone_descriptors exactly — if the brand is 'warm, handmade, "
        "artisan', the caption must read like a person talking, not a brand posting. "
        "Keep sentence structure short (≤12 words per sentence). "
        "Preserve the hook pattern — only swap vocabulary, do not restructure."
    ),
    "wrong_platform": (
        "Restructure for Instagram specifically: "
        "(1) Hook goes on the FIRST line, before the 'more' cutoff (~125 chars). "
        "(2) Use 2-3 intentional line breaks for white space readability. "
        "(3) Place 5-10 hashtags at the very end, not inline. "
        "(4) CTA must be ONE specific action — save, share, comment with a word, "
        "or DM — never 'follow for more' or 'like if you agree'. "
        "(5) Keep total length under 2,200 characters."
    ),
    "factual_gap": None,  # escalates to human_review_flag, no auto-rewrite
    "approved": None,  # no action needed
}

# ---------------------------------------------------------------------------
# Classifier prompt (Granite #21)
# Extended with hook-pattern examples so Granite distinguishes structural
# genericness from vocabulary genericness.
# ---------------------------------------------------------------------------

_CLASSIFIER_TEMPLATE = """\
You are an editorial quality gate. You receive a caption and a list of brand-voice \
issues identified by a reviewer. Your ONLY job is to classify the PRIMARY failure mode.

Caption:
"{caption}"

Issues identified:
{issues_block}

Classify the primary failure mode as ONE of:
  ai_slop         — generic, template-like, or "obviously AI" language.
                    This includes: greetings as openers ("Hi guys", "Welcome back"),
                    filler superlatives ("amazing quality", "delicious treats",
                    "game-changer", "in today's fast-paced world"), or captions that
                    state what the creator WILL do rather than a result the viewer GETS.
                    A caption CAN have a strong hook and still be ai_slop in the body.
  off_brand_vocab — specific terms or tone that violate brand guidelines
                    (avoided terms present, wrong tone descriptor, wrong register).
  wrong_platform  — formatting wrong for Instagram
                    (too long, no line breaks, too many/few hashtags, wrong CTA style).
  factual_gap     — specific factual claims that cannot be verified
                    (temperatures, times, measurements stated as fact without basis).
  approved        — no significant issues found across hook, body, CTA, and formatting.

Return ONLY valid JSON — no preamble, no markdown fences:
{{
  "error_type": "<one of the five labels above>",
  "flagged_phrase": "<shortest phrase in the caption that best illustrates the issue, or empty string if approved>",
  "fix_direction": "<one sentence describing exactly what to fix, or 'none' if approved>"
}}
"""

_CLASSIFIER_PROMPT = PromptTemplate(
    input_variables=["caption", "issues_block"],
    template=_CLASSIFIER_TEMPLATE,
)

_VALID_ERROR_TYPES = frozenset(
    {"ai_slop", "off_brand_vocab", "wrong_platform", "factual_gap", "approved"}
)


# ---------------------------------------------------------------------------
# JSON parsing helpers (unchanged from original)
# ---------------------------------------------------------------------------


def _repair_missing_commas(text: str) -> str:
    return re.sub(
        r'"(\s+)"([A-Za-z_][A-Za-z0-9_ ]*)"(\s*):',
        r'",\1"\2"\3:',
        text,
    )


def _parse_json(raw: str) -> dict:
    text = re.sub(r"^```(?:json)?|```$", "", raw.strip(), flags=re.MULTILINE).strip()
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        pass
    try:
        return json.loads(_repair_missing_commas(text))
    except json.JSONDecodeError:
        pass
    # Last resort: regex field extraction
    et = re.search(r'"error_type"\s*:\s*"([^"]+)"', text)
    fp = re.search(r'"flagged_phrase"\s*:\s*"([^"]*)"', text)
    fd = re.search(r'"fix_direction"\s*:\s*"([^"]*)"', text)
    if et:
        return {
            "error_type": et.group(1),
            "flagged_phrase": fp.group(1) if fp else "",
            "fix_direction": fd.group(1) if fd else "",
        }
    return {}


# ---------------------------------------------------------------------------
# CriticAgent
# ---------------------------------------------------------------------------


class CriticAgent(BaseAgent):
    name = "CriticAgent"

    def __init__(self, memory=None, model: str = OLLAMA_MODEL):
        super().__init__(memory, model)
        from src.generation.brand_guardian import BrandGuardian

        self._guardian = BrandGuardian(model=model)
        self._llm = OllamaLLM(model=model, temperature=0.1, num_predict=200)
        self._chain = _CLASSIFIER_PROMPT | self._llm

    # ------------------------------------------------------------------
    def run(self, task: AgentTask) -> AgentResult:
        if task.task_type != "critique":
            return AgentResult(
                agent_name=self.name,
                success=False,
                error_message=f"CriticAgent only handles 'critique', got '{task.task_type}'",
            )
        return self._critique(task.payload)

    # ------------------------------------------------------------------
    def _critique(self, payload: dict) -> AgentResult:
        caption = payload.get("caption", "")
        cluster_id = payload.get("cluster_id", 0)

        # Step 1 — BrandGuardian identifies issues (Granite #18)
        critique = self._guardian.critique(caption, cluster_id)
        verdict = critique.get("verdict", "needs_revision")
        issues = critique.get("issues", [])

        # Fast-path: guardian already approved, skip classifier
        if verdict == "approve" and not issues:
            return AgentResult(
                agent_name=self.name,
                output={
                    "guardian_critique": critique,
                    "error_type": "approved",
                    "flagged_phrase": "",
                    "fix_direction": "none",
                    "granite_fix_hint": "none",
                },
                error_type="approved",
                routing_target=None,
            )

        # Step 2 — ErrorClassifier maps issues to a typed error (Granite #21)
        issues_block = "\n".join(
            f"- {i}"
            for i in (issues or ["Generic or template-like language detected."])
        )
        error_type, flagged_phrase, granite_fix_hint = self._classify(
            caption, issues_block
        )

        # Step 3 — Override fix_direction with the deterministic signal directive.
        # granite_fix_hint is preserved in output for logging/debugging.
        structured_direction = _SIGNAL_REPAIR_DIRECTIVES.get(error_type)
        fix_direction = (
            structured_direction if structured_direction else granite_fix_hint
        )

        return AgentResult(
            agent_name=self.name,
            output={
                "guardian_critique": critique,
                "error_type": error_type,
                "flagged_phrase": flagged_phrase,
                "fix_direction": fix_direction,  # structured → CopywritingAgent uses this
                "granite_fix_hint": granite_fix_hint,  # Granite's raw suggestion → logging only
                "severity": critique.get("severity", "minor"),
            },
            error_type=error_type,
            routing_target=ROUTING_TARGETS.get(error_type),
        )

    # ------------------------------------------------------------------
    def _classify(self, caption: str, issues_block: str) -> tuple[str, str, str]:
        """Run the error type classifier. Falls back to ai_slop on parse failure."""
        try:
            raw = self._chain.invoke({"caption": caption, "issues_block": issues_block})
            result = _parse_json(raw)
            etype = result.get("error_type", "ai_slop")
            if etype not in _VALID_ERROR_TYPES:
                etype = "ai_slop"
            return (
                etype,
                str(result.get("flagged_phrase", "")),
                str(result.get("fix_direction", "Rewrite to remove generic language.")),
            )
        except Exception:
            return ("ai_slop", "", "Rewrite to remove generic language.")
